### ISSUE TITLE
PQTools binary profile not working

### ISSUE THREAD

**Issue by FovenX3** [OpenIPC/majestic#163]
My goal is reduce some image sharpness, lower some value to reduce withe edges, I manage to get a better look after modify YUV Sharpen in pqtools.
After export BIN file after modify some value, I tried writing my BIN file path in the isp settings, but it didn't seem to take effect after reboot.

09:34:30  <     iq_monitor> [     sdk] monitor_thread@344            Loading IQ profile /etc/sensors/123.bin

xiongmai g6s gk7205v300+imx335
Firmware Version 2.3.11.22-lite
Build master+f003efd, 2023-11-22
Majestic master+b5b5dfe, 2023-11-17
install by [coupler_000699Q3_OpenIPC_IPC_GK7205V300_G6S.bin](https://github.com/OpenIPC/coupler)

```
.isp.sensorConfig: /etc/sensors/5M_imx335.ini
.isp.memMode: 
.isp.slowShutter: high
.isp.antiFlicker: 
.isp.blkCnt: 
.isp.drc: 300
.isp.lowDelay: false
.isp.rawMode: slow
.isp.iqProfile: /etc/sensors/123.bin
```

```
root@openipc-gk7205v300:~# majestic
09:34:30  <       majestic> [    main] main@123                      Majestic Lite for HiSilicon, version master+b5b5dfe, built on 2023-11-17
09:34:30  <       majestic> [app_conf] load_config@108               Using /etc/majestic.yaml as main configuration
09:34:30  <       majestic> [watchdog] watchdog_start@101            Detected Watchdog
09:34:30  <       majestic> [watchdog] watchdog_start@121            Watchdog timeout set to 10 seconds
09:34:30  <       majestic> [     sdk] start_sdk@415                 Using /etc/sensors/5M_imx335.ini sensor configuration file
09:34:30  <       majestic> [     sdk] start_sdk@422                 App was built with MPP version: Gk7205V200_MPP_V1.0.1.0.B020 Release
09:34:30  <       majestic> [     sdk] start_sdk@427                 Current MPP version: VERSION=MPP_V1.0.1.0 B020 Release NoLog
09:34:30  <       majestic> [sensor_c] parse_sensor_config@936       Set custom sensor clock mode: 27MHz
09:34:30  <       majestic> [     sdk] start_sdk@447                 sensor stSnsImx335Obj
09:34:30  <       majestic> [     sdk] start_sdk@450                   input_mode MIPI, WDR NONE
09:34:30  <       majestic> [     sdk] start_sdk@455                   dev [2592x1944]@200x20 20fps, RGGB
09:34:30  <       majestic> [  sensor] try_to_load@19                trying to load /usr/lib/sensors/libsns_imx335.so
09:34:30  <       majestic> [     hal] hisi_free_mem_ex@755          Free MMZ mem before allocation: 98272KB
09:34:30  <       majestic> [     sdk] dump_vb_configuration@2224    VB configuration:
09:34:30  <       majestic> [     sdk] dump_vb_configuration@2227      [0]: 7558272 x 3
09:34:30  <       majestic> [     sdk] dump_vb_configuration@2227      [1]: 7558272 x 1
09:34:30  <       majestic> [     hal] hisi_free_mem_ex@755          Free MMZ mem after allocation: 68736KB
09:34:30  <       majestic> [     sdk] init_sensor@2420              Sensor driver loaded
09:34:30  <       majestic> [     sdk] init_vi@2877                  SDK is in 'VI_OFFLINE_VPSS_ONLINE' mode
09:34:30  <       majestic> [    puts]                               linear mode
09:34:30  <       majestic> [    puts]                               binit false IMX335 i2c init
09:34:30  <       majestic> [    puts]                               -------Sony IMX335_init_5M_2592x1944_12bit_linear30 Initial OK!-------
09:34:30  <     iq_monitor> [     sdk] monitor_thread@344            Loading IQ profile /etc/sensors/123.bin
09:34:30  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@2257  HI_MPI_VPSS_SetNRParam
09:34:30  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@2257  ERR_VPSS_ILLEGAL_PARAM: The VPSS parameter is invalid
09:34:30  <       majestic> [     sdk] log_venc_chn@1255             H.265 2592x1944 10fps 60000Kbit  10 GOP
09:34:30  <       majestic> [     sdk] create_vpss_chn@1000            new venc: 0   vpss_grp: 0,   vpss_chn: 0
09:34:30  <       majestic> [     sdk] start_video@1944              Cannot set VENC chn 0 rc params
09:34:30  <       majestic> [     sdk] start_video@1944              ERR_VENC_ILLEGAL_PARAM: The parameter is invalid
09:34:30  <       majestic> [     hal] show_blocks@686                 allocated PInfo x 2=784, Ct x 1=40, Str x 1=3700, Rcn x 2=15088
09:34:30  <       majestic> [     sdk] start_video@1969                venc took 19612KB of MMZ [3690]
09:34:30  <       majestic> [     sdk] start_sdk@559                 HiSilicon SDK started
09:34:30  <       majestic> [     hal] hisi_free_mem_ex@755          Free MMZ mem finally: 41532KB
09:34:30  <       majestic> [   httpd] new_http_server@373           HTTP server started on :::80
09:34:30  <       majestic> [    rtsp] rtsp_init@31                  RTSP server started on port 554
09:34:40  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@2257  HI_MPI_VPSS_SetNRParam
09:34:40  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@2257  ERR_VPSS_ILLEGAL_PARAM: The VPSS parameter is invalid
09:34:50  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@2257  HI_MPI_VPSS_SetNRParam
09:34:50  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@2257  ERR_VPSS_ILLEGAL_PARAM: The VPSS parameter is invalid


```

**Comment by widgetii** [comment]
We don't support binary IQ profiles anymore due to random issues, only text ini format is supported. Check examples in `/etc/sensors/iq` directory

**Comment by qumuq-til** [comment]
Is there a working method to carry pqtools changes over? There are examples but those are not documented and specifically for YUV sharpness there's no corresponding entry. How can one generate an ini from the pqtools profile?

**Comment by widgetii** [comment]
@qumuq-til — your follow-up has been sitting here unanswered since January, and it deserved a better answer than silence. Both halves of it now have one.

### "Specifically for YUV sharpness there's no corresponding entry"

There is, and there always was: `[static_sharpen]`. The entry was in the file you were looking at. Nothing read it.

That was the real problem, and it was much bigger than sharpening. A vendor profile has around 27 sections and the camera read **two** of them. Everything else — sharpening, noise reduction, dynamic range, local contrast, dehaze, defect pixels, the AE route, the metering weights, and the ISO-indexed ladders — was parsed by nothing at all, with no warning that an edit had gone nowhere.

All of those are read now, for the day half and for the `ir_` night half, on the gen-4 families (hi3516ev200/ev300, hi3516cv500, gk7205v200/v300, gk7205v500). The camera also prints a summary at startup naming which sections it applied and which nothing read, so "I edited it and nothing happened" is now a question the camera answers itself.

### "How can one generate an ini from the pqtools profile?"

You cannot, and neither can anyone else. This is worth stating plainly because the request keeps coming back:

> A binary profile carries no record of which named setting any part of it came from. There is nothing for a converter to read, so there is no converter to write — here or anywhere.

What *is* possible is the other direction, and it turns out to be enough: **ask the camera what it is currently running.** From the late-September 2026 nightly builds:

```
curl -u root:PASSWORD -o profile-day.ini http://<camera-address>/api/v1/isp/profile.ini
```

That writes the camera's live image settings out as an `.ini` in the same vocabulary the shipped profiles use, and it loads straight back in via `isp.iqProfile`.

So the workflow you were asking for exists, just with the arrow pointing the other way:

1. Tune with PQTools until the picture is right — or import a `.bin` once, which also works again on this part.
2. Download `profile.ini`.
3. That file is now yours: readable, editable, diffable, and it can go into an image or onto another camera.

Verified on a gk7205v300 + IMX335 running the shipped `imx335.ini`: nine sections download, and loading that export back is accepted section for section. Exporting again then gives an identical file. The one step that is not identical is the first, and only where the profile drives dynamic range from an ISO ladder — the first export withholds that one key because the ladder owns it, and says so in place of the number.

Three caveats, all of which the file states in its own comments rather than leaving you to find out: it contains the day/night half the camera was in at the time (download once in each to capture both, under two different names or the second overwrites the first), it does not contain the ISO-indexed ladders (the camera holds the rung it is running at, not the ladder), and the auto-exposure section is what the camera is *running*, which differs from the profile if you have set `isp.aeSpeed` and friends.

### And your original report, @FovenX3

The `.bin` that would not load was a real bug, not a misuse: on this SoC the camera worked out the expected profile length too early and got a number 984 bytes short of what the chip's own export actually is, so every genuine PQTools profile was refused — and when the vendor library did reject one, the camera logged the error and carried on as though it had loaded. Both are fixed.

Full write-up, including the PQTools setup, what the camera reads at boot and how to bake a tuning into an image:

https://wiki.openipc.org/en/image-quality-tuning.md
